language: java
services:
  - postgresql
before_install:
- export PGPASSWORD="postgres"
- psql -c "create database invoicify" -U postgres

deploy:
  provider: heroku
  on:
    branch: master
  api_key:  
    secure: "acfbdd08-3b5d-48fa-9ca2-89477111c059"
    
