language: java
services:
  - postgresql
before_install:
- export PGPASSWORD="postgres"
- psql -c "create database invoicify" -U postgres

deploy:
  provider: heroku
  on:
    branch: master
  api_key:  
    secure: qdKatKDbeMsDZwz2sUtVhg
    
